name: Collect repository insights

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Collect insights
        id: collect-insights
        uses: polygenelubricants/repository-insight-tracker@v1.0.0
        with:
          github-token: ${{ secrets.INSIGHTS }}
          branch: 'repository-insights'
          format: 'csv'
          directory: '.insights'
      - name: Write insights to console
        run: |
          echo "Stargazers: ${{ steps.collect-insights.outputs.stargazers }}"
          echo "Commits: ${{ steps.collect-insights.outputs.commits }}"
          echo "Contributors: ${{ steps.collect-insights.outputs.contributors }}"
          echo "Traffic Views Yesterday: ${{ steps.collect-insights.outputs.traffic_views }}"
          echo "Unique Traffic Views Yesterday: ${{ steps.collect-insights.outputs.traffic_uniques }}"
          echo "Clones Yesterday: ${{ steps.collect-insights.outputs.clones_count }}"
          echo "Unique Clones Yesterday: ${{ steps.collect-insights.outputs.clones_uniques }}"
